---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - cron
      - curl
      - git
      - jq
      - mosh
      - ufw
      - ansible-lint
      - cockpit-bridge

- name: Check if running in test container
  ansible.builtin.stat:
    path: /etc/skel/armarserver
  register: container_result

- name: Install firefox snap
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Disable firefox snap service
      ansible.builtin.command: systemctl disable --now var-snap-firefox-common-host\\x2dhunspell.mount
      register: unmount_firefox
      failed_when: unmount_firefox.rc < 1

    - name: Remove firefox snap
      community.general.snap:
        name: firefox
        state: absent
      when: not container_result.stat.exists  # i.e. assume snap isn't installed in container

    - name: Disallow apt from installing firefox via snap
      ansible.builtin.copy:
        src: apt/mozilla-firefox
        dest: /etc/apt/preferences.d/mozilla-firefox
        mode: "0755"

    - name: Add mozilla ppa
      ansible.builtin.apt_repository:
        repo: ppa:mozillateam/ppa

    - name: Install Firefox
      ansible.builtin.apt:
        name: firefox

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Enable and start Docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: started
    enabled: true
