---
# Install dependencies
- ansible.builtin.include_tasks: deps.yml

# Create users, omit `github` parameter if user does not have a GitHub account
- ansible.builtin.include_tasks: user.yml
  loop:
    - { name: 'githubactions', admin: true, docker: true, github: 'heywoodlh' }
    - { name: 'scott', admin: true, docker: true, github: 'ScottX01' }
    - { name: 'heywoodlh', admin: true, docker: true, github: 'heywoodlh' }

# Setup cron jobs
- ansible.builtin.include_tasks: cron.yml

# Configure scripts
- ansible.builtin.include_tasks: scripts.yml

# Setup xrdp for list of users
- ansible.builtin.include_tasks: xrdp.yml
  loop:
    - scott
    - heywoodlh

# Configure basic security posture
- ansible.builtin.include_tasks: security.yml

# Install Nix
- ansible.builtin.include_tasks: nix.yml

# Host-specific tasks
# reddawnmilsim server tasks
- ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - "hosts/reddawnmilsim.yml"
    - "./reforger.yml"
  when: ansible_hostname == "reddawnmilsim"
  vars:
    linuxgsm_user: scott
    linuxgsm_home: "/home/scott"

# reddawnpvp server tasks
- ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - "./reforger.yml"
  when: ansible_hostname == "reddawnpvp"
  vars:
    linuxgsm_user: scott
    linuxgsm_home: "/home/scott"
