---
- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow port range 60000-61000 for mosh
  community.general.ufw:
    rule: allow
    port: 60000:61000
    proto: udp

- name: Rate limit SSH (reduces brute force efficacy)
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Check if running in test container
  ansible.builtin.stat:
    path: /etc/skel/armarserver
  register: container_result

- name: Enable ufw
  community.general.ufw:
    state: enabled
  when: not container_result.stat.exists
