---
- name: "Create user {{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash

- name: "Allow user to sudo without password: {{ item.name }}"
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item.name }}"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    mode: "0600"
  when:
    - item.admin is defined
    - item.admin == "true"

- name: "Ensure .ssh folder exists for user: {{ item.name }}"
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ item.name }}"

- name: Check if running in test container
  ansible.builtin.stat:
    path: /etc/skel/armarserver
  register: container_result

- name: "Copy cockpit SSH key to user"
  ansible.builtin.copy:
    src: /home/cockpit/.ssh/id_ed25519
    dest: "/home/{{ item.name }}/.ssh/id_ed25519"
    mode: "0600"
    remote_src: true
  when:
    - not container_result.stat.exists
    - item.admin is defined
    - item.admin == "true"
    - ansible_hostname == "red-dawn-mgmt"

- name: "Add user to docker group: {{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: docker
    append: true
  when:
    - item.docker is defined
    - item.docker == "true"

- name: Add user GitHub keys to authorized_keys
  ansible.posix.authorized_key:
    key: "https://github.com/{{ item.github }}.keys"
    user: "{{ item.name }}"
  when: item.github is defined

- name: Add githubactions key to githubactions user
  ansible.posix.authorized_key:
    key: "{{ lookup('file', 'public_keys/githubactions') }}"
    user: githubactions
  when: item.name == "githubactions"

- name: Add cockpit key to cockpit user
  ansible.posix.authorized_key:
    key: "{{ lookup('file', 'public_keys/cockpit') }}"
    user: cockpit
  when: item.name == "cockpit"
