name: Test Ansible playbooks
on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - '**.yml'
  workflow_dispatch:

env:
  SKIP_ANSIBLE_LINT: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.8.1
        with:
          args: "-c .ansible-lint main.yml tasks/*"
          setup_python: "true"
          requirements_file: ./requirements.yml

      - name: Run tests
        run: |
          script -e -c "./test.sh"
